---
title: "Estudio Estadístico Sobre la Presencia de Sesgo Crítico en Reseñas Musicales de Pitchfork.com"
author: "Armando Delfin, Gabriel Di Buongrazio y Miguel Rodriguez"
format: pdf
---

```{r setup, include=FALSE, echo=FALSE}


knitr::opts_chunk$set(echo = TRUE)

 

```

"Universidad Central de Venezuela (UCV), Escuela de Estadística y Ciencias Actuariales"

\

\

\

\

\

\

\

\

::: {style="text-align: left; position: absolute; top: 20px; left: 20px;"}
**Docente:**

\
Jesus Ochoa
:::

\

## Introducción

Aquí irá toda la introducción!

## Contenido

### 1. Muestra de datos

Grafico Average

```{r, echo=FALSE}
#| label: load_libraries
#| message: false
#| warning: false

if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse, pacman, DescTools, moments, forcats, scales, DBI, RSQLite, dbplyr, odbc, flextable,
  ftExtra, svglite
)
```

```{r, echo=FALSE}
#| label: connect_database
#| message: false
#| warning: false


# Formato de la ruta : "C:/users/*tu nombre de usuario*/*La carpeta de la db*/*nombre de la db*

# Ruta a la base de datos (asegúrate de que sea correcta)
db_path <- "C:/Users/migue/OneDrive/Documentos/GitHub/ProyectoCompu-II-GR6/database.sqlite"
# Establecer la conexión
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = db_path)

# Importante usar la función dbDisconnect(con) antes de cerrar la sesión de R.

```

```{r, echo=FALSE}
#| label: graphics_Average
#| message: false
#| warning: false

ggplot(tb_2, aes(x = reorder(genre, N), na.rm = TRUE, y = avg)) +
  geom_col(fill = "blue") + theme_minimal()
```

Grafico Proporciones de Best new Music.

```{r, echo=FALSE}
#| label: graphics_Proporciones 
#| message: false
#| warning: false
ggplot(tb_best, aes(x = fct_infreq(genre), y = after_stat(prop), group = 1)) +
  geom_bar( fill = "lightpink", colour = "darkgray") + theme_minimal() +
  scale_y_continuous(labels = scales::percent)

```

## Conclusión

Aquí irá toda la conclusión!

## Bibliografía

Aquí irá toda la bibliografía!
